"""initial schema

Revision ID: 531baa5b302b
Revises: 
Create Date: 2026-09-19 15:52:51.538904
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '531baa5b302b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sika_id', sa.String(length=16), nullable=True),
    sa.Column('sector_code', sa.String(length=8), nullable=True),
    sa.Column('sector_name', sa.String(length=80), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('shares_outstanding', sa.BigInteger(), nullable=True),
    sa.Column('float_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('is_suspended', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_ticker'), 'company', ['ticker'], unique=True)
    op.create_table('digest',
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('market_text', sa.Text(), nullable=False),
    sa.Column('built_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('session_date')
    )
    op.create_table('index_quote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index_name', sa.String(length=80), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('prev_close', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('close', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('change_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('ytd_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('per_avg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index_name', 'session_date', name='uq_index_name_date')
    )
    op.create_index(op.f('ix_index_quote_index_name'), 'index_quote', ['index_name'], unique=False)
    op.create_index(op.f('ix_index_quote_session_date'), 'index_quote', ['session_date'], unique=False)
    op.create_table('ingest_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rows', sa.Integer(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingest_run_job'), 'ingest_run', ['job'], unique=False)
    op.create_table('market_day',
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('market_cap', sa.BigInteger(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('value_fcfa', sa.BigInteger(), nullable=True),
    sa.Column('advancers', sa.Integer(), nullable=True),
    sa.Column('decliners', sa.Integer(), nullable=True),
    sa.Column('unchanged', sa.Integer(), nullable=True),
    sa.Column('market_per', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('market_yield', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('session_date')
    )
    op.create_table('tariff',
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('action')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=True),
    sa.Column('language', sa.String(length=5), server_default='fr', nullable=False),
    sa.Column('goal', sa.String(length=20), nullable=True),
    sa.Column('horizon', sa.String(length=20), nullable=True),
    sa.Column('capital_range', sa.String(length=20), nullable=True),
    sa.Column('sgi_name', sa.String(length=80), nullable=True),
    sa.Column('digest_subscribed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('onboarding_step', sa.String(length=20), server_default='start', nullable=False),
    sa.Column('is_blocked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=True)
    op.create_table('advice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('price_at_advice', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('full', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advice_company_id'), 'advice', ['company_id'], unique=False)
    op.create_index(op.f('ix_advice_user_id'), 'advice', ['user_id'], unique=False)
    op.create_table('corporate_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('factor', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corporate_action_company_id'), 'corporate_action', ['company_id'], unique=False)
    op.create_table('credit_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=True),
    sa.Column('reference', sa.String(length=80), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ledger_user_created', 'credit_ledger', ['user_id', 'created_at'], unique=False)
    op.create_index('uq_ledger_recharge_reference', 'credit_ledger', ['reference'], unique=True, postgresql_where=sa.text("kind = 'recharge'"))
    op.create_table('daily_official',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('close', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('ref_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('per', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dividend_net', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('ex_dividend_date', sa.Date(), nullable=True),
    sa.Column('yield_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('ytd_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('is_suspended', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'session_date', name='uq_official_company_date')
    )
    op.create_index(op.f('ix_daily_official_company_id'), 'daily_official', ['company_id'], unique=False)
    op.create_index(op.f('ix_daily_official_session_date'), 'daily_official', ['session_date'], unique=False)
    op.create_table('daily_quote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('high', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('low', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('close', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('prev_close', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('value_fcfa', sa.BigInteger(), nullable=True),
    sa.Column('change_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('adjusted_factor', sa.Numeric(precision=12, scale=6), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'session_date', name='uq_quote_company_date')
    )
    op.create_index(op.f('ix_daily_quote_company_id'), 'daily_quote', ['company_id'], unique=False)
    op.create_index(op.f('ix_daily_quote_session_date'), 'daily_quote', ['session_date'], unique=False)
    op.create_table('dividend_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('yield_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'ex_date', name='uq_dividend_company_date')
    )
    op.create_index(op.f('ix_dividend_event_company_id'), 'dividend_event', ['company_id'], unique=False)
    op.create_table('fundamental',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('revenue_growth', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('net_income', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('net_income_growth', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('eps', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('per', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dividend', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'fiscal_year', name='uq_fundamental_company_year')
    )
    op.create_index(op.f('ix_fundamental_company_id'), 'fundamental', ['company_id'], unique=False)
    op.create_table('indicator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('ma20', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('ma50', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('rsi14', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('high_52w', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('low_52w', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('avg_volume_20', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('volume_ratio', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('per', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('yield_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('sector_per_avg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'session_date', name='uq_indicator_company_date')
    )
    op.create_index(op.f('ix_indicator_company_id'), 'indicator', ['company_id'], unique=False)
    op.create_index(op.f('ix_indicator_session_date'), 'indicator', ['session_date'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=3), nullable=False),
    sa.Column('channel_msg_id', sa.String(length=120), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('media_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('credits_charged', sa.Integer(), server_default='0', nullable=False),
    sa.Column('trace_id', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_msg_id')
    )
    op.create_index(op.f('ix_message_user_id'), 'message', ['user_id'], unique=False)
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_news_company_id'), 'news', ['company_id'], unique=False)
    op.create_index(op.f('ix_news_published_at'), 'news', ['published_at'], unique=False)
    op.create_table('outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('dedupe_key', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    op.create_index(op.f('ix_outbox_scheduled_for'), 'outbox', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_outbox_status'), 'outbox', ['status'], unique=False)
    op.create_index(op.f('ix_outbox_user_id'), 'outbox', ['user_id'], unique=False)
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_ref', sa.String(length=80), nullable=False),
    sa.Column('amount_fcfa', sa.Integer(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_ref')
    )
    op.create_index(op.f('ix_payment_user_id'), 'payment', ['user_id'], unique=False)
    op.create_table('position',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('avg_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'company_id')
    )
    op.create_table('user_memory',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'key')
    )
    op.create_table('watchlist',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'company_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist')
    op.drop_table('user_memory')
    op.drop_table('position')
    op.drop_index(op.f('ix_payment_user_id'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_outbox_user_id'), table_name='outbox')
    op.drop_index(op.f('ix_outbox_status'), table_name='outbox')
    op.drop_index(op.f('ix_outbox_scheduled_for'), table_name='outbox')
    op.drop_table('outbox')
    op.drop_index(op.f('ix_news_published_at'), table_name='news')
    op.drop_index(op.f('ix_news_company_id'), table_name='news')
    op.drop_table('news')
    op.drop_index(op.f('ix_message_user_id'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_indicator_session_date'), table_name='indicator')
    op.drop_index(op.f('ix_indicator_company_id'), table_name='indicator')
    op.drop_table('indicator')
    op.drop_index(op.f('ix_fundamental_company_id'), table_name='fundamental')
    op.drop_table('fundamental')
    op.drop_index(op.f('ix_dividend_event_company_id'), table_name='dividend_event')
    op.drop_table('dividend_event')
    op.drop_index(op.f('ix_daily_quote_session_date'), table_name='daily_quote')
    op.drop_index(op.f('ix_daily_quote_company_id'), table_name='daily_quote')
    op.drop_table('daily_quote')
    op.drop_index(op.f('ix_daily_official_session_date'), table_name='daily_official')
    op.drop_index(op.f('ix_daily_official_company_id'), table_name='daily_official')
    op.drop_table('daily_official')
    op.drop_index('uq_ledger_recharge_reference', table_name='credit_ledger', postgresql_where=sa.text("kind = 'recharge'"))
    op.drop_index('ix_ledger_user_created', table_name='credit_ledger')
    op.drop_table('credit_ledger')
    op.drop_index(op.f('ix_corporate_action_company_id'), table_name='corporate_action')
    op.drop_table('corporate_action')
    op.drop_index(op.f('ix_advice_user_id'), table_name='advice')
    op.drop_index(op.f('ix_advice_company_id'), table_name='advice')
    op.drop_table('advice')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_table('user')
    op.drop_table('tariff')
    op.drop_table('market_day')
    op.drop_index(op.f('ix_ingest_run_job'), table_name='ingest_run')
    op.drop_table('ingest_run')
    op.drop_index(op.f('ix_index_quote_session_date'), table_name='index_quote')
    op.drop_index(op.f('ix_index_quote_index_name'), table_name='index_quote')
    op.drop_table('index_quote')
    op.drop_table('digest')
    op.drop_index(op.f('ix_company_ticker'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
